
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qrder?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: qrderadmin
    password: "qrder"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect